N=chr(10); Q=chr(34)
L=[]; L.append(N)
L.append('    pairs = []')
L.append('    if config.llm_primary_api_key:')
L.append('        p = _build(config.llm_primary_api_key, config.llm_primary_model, config.llm_primary_base_url, config.llm_primary_api_type)')
L.append('        if p: pairs.append(p)')
L.append('    if config.llm_fallback_api_key:')
L.append('        p = _build(config.llm_fallback_api_key, config.llm_fallback_model, config.llm_fallback_base_url, config.llm_fallback_api_type)')
L.append('        if p: pairs.append(p)')
open('D:/zhangxuefengagent/src/api/llm_client.py','a',encoding='utf-8').write(N.join(L))
print('ok')
